In [1]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

In [2]:
train = pd.read_csv("iris_train.csv")
test = pd.read_csv("iris_test.csv")

In [3]:
train.head()

,id,species,sepal length (cm),petal length (cm),sepal width (cm),petal width (cm)
0,0,setosa,4.4,1.4,2.9,0.2
1,1,versicolor,6.4,4.5,3.2,1.5
2,2,virginica,6.2,4.8,2.8,1.8
3,3,virginica,7.2,6.1,3.6,2.5
4,4,setosa,4.9,1.4,3.0,0.2

In [4]:
test.head()

   id    species  sepal length (cm)  petal length (cm)
0   0     setosa                5.4                1.7
1   1     setosa                5.7                1.5
2   2     setosa                5.3                1.5
3   3     setosa                5.1                1.9
4   4  virginica                6.0                4.8

In [19]:
from ngboost import NGBRegressor
from catboost import CatBoostRegressor
from xgboost import XGBRegressor
from lightgbm import LGBMRegressor
from sklearn.ensemble import *
from sklearn.linear_model import Ridge, Lasso

from sklearn.model_selection import KFold, StratifiedKFold, LeaveOneOut
from sklearn.metrics import mean_squared_error, mean_absolute_error
from sklearn.preprocessing import LabelEncoder

In [6]:
lo = LeaveOneOut()
kf = KFold(n_splits = 5, random_state = 42, shuffle = True)

In [7]:
train.groupby('species')['sepal width (cm)'].mean()

species
setosa        3.346667
versicolor    2.790000
virginica     2.933333
Name: sepal width (cm), dtype: float64

In [8]:
train.groupby('species')['petal width (cm)'].mean()

species
setosa        0.200000
versicolor    1.353333
virginica     2.006667
Name: petal width (cm), dtype: float64

In [9]:
train['sep_w'] = train['species'].map({'setosa' : 3, 'versicolor' : 1, 'virginica' : 2})
test['sep_w'] = test['species'].map({'setosa' : 3, 'versicolor' : 1, 'virginica' : 2})

In [10]:
train['pet_w'] = train['species'].map({'setosa' : 1, 'versicolor' : 2, 'virginica' : 3})
test['pet_w'] = test['species'].map({'setosa' : 1, 'versicolor' : 2, 'virginica' : 3})

In [11]:
X = train.drop(['species', 'sepal width (cm)', 'petal width (cm)'], axis = 1)
y1 = train.iloc[:, 4]
y2 = train.iloc[:, 5]

In [12]:
target = test[X.columns]

In [16]:
rf_pred1 = np.zeros((target.shape[0]))
for i, idx in enumerate(zip(lo.split(X, y1))) :
    print(f'{i + 1} FOLD Start!')
    tr_x, tr_y = X.iloc[idx[0][0]], y1.iloc[idx[0][0]]
    val_x, val_y = X.iloc[idx[0][1]], y1.iloc[idx[0][1]]
    
    rf = RandomForestRegressor(random_state = 42, n_estimators = 100, criterion = 'mae', max_depth = 4)
    
    rf.fit(tr_x, tr_y)
    val_pred = rf.predict(val_x)
    val_mae = mean_absolute_error(val_y, val_pred)
    print(f'VAL MAE = {val_mae}')
    fold_pred = rf.predict(target) / 75
    
    rf_pred1 += fold_pred
    
    print('\n')

1 FOLD Start!
VAL MAE = 0.20349999999999868


2 FOLD Start!
VAL MAE = 0.24749999999999783


3 FOLD Start!
VAL MAE = 0.056999999999999496


4 FOLD Start!
VAL MAE = 0.5900000000000003


5 FOLD Start!
VAL MAE = 0.08749999999999947


6 FOLD Start!
VAL MAE = 0.08499999999999996


7 FOLD Start!
VAL MAE = 0.2199999999999993


8 FOLD Start!
VAL MAE = 0.023499999999998966


9 FOLD Start!
VAL MAE = 0.21700000000000008


10 FOLD Start!
VAL MAE = 0.03799999999999848


11 FOLD Start!
VAL MAE = 0.5965000000000003


12 FOLD Start!
VAL MAE = 0.2390000000000012


13 FOLD Start!
VAL MAE = 0.4514999999999971


14 FOLD Start!
VAL MAE = 0.05899999999999794


15 FOLD Start!
VAL MAE = 0.5595000000000017


16 FOLD Start!
VAL MAE = 0.04550000000000143


17 FOLD Start!
VAL MAE = 0.608000000000001


18 FOLD Start!
VAL MAE = 0.001500000000000501


19 FOLD Start!
VAL MAE = 0.14050000000000074


20 FOLD Start!
VAL MAE = 0.14899999999999913


21 FOLD Start!
VAL MAE = 0.3720000000000008


22 FOLD Start!
VAL MAE = 0.44800000000000173


23 FOLD Start!
VAL MAE = 0.2839999999999989


24 FOLD Start!
VAL MAE = 0.691000000000003


25 FOLD Start!
VAL MAE = 0.024499999999999744


26 FOLD Start!
VAL MAE = 0.1844999999999999


27 FOLD Start!
VAL MAE = 0.23199999999999932


28 FOLD Start!
VAL MAE = 0.22850000000000037


29 FOLD Start!
VAL MAE = 0.2245000000000008


30 FOLD Start!
VAL MAE = 0.8894999999999991


31 FOLD Start!
VAL MAE = 0.054500000000001325


32 FOLD Start!
VAL MAE = 0.015499999999999403


33 FOLD Start!
VAL MAE = 0.4029999999999987


34 FOLD Start!
VAL MAE = 0.5444999999999989


35 FOLD Start!
VAL MAE = 0.2729999999999988


36 FOLD Start!
VAL MAE = 0.4720000000000022


37 FOLD Start!
VAL MAE = 0.20800000000000018


38 FOLD Start!
VAL MAE = 0.14499999999999913


39 FOLD Start!
VAL MAE = 0.2410000000000001


40 FOLD Start!
VAL MAE = 0.0015000000000000568


41 FOLD Start!
VAL MAE = 0.2234999999999987


42 FOLD Start!
VAL MAE = 0.3129999999999993


43 FOLD Start!
VAL MAE = 0.09049999999999825


44 FOLD Start!
VAL MAE = 0.06899999999999995


45 FOLD Start!
VAL MAE = 0.006500000000001727


46 FOLD Start!
VAL MAE = 0.44800000000000084


47 FOLD Start!
VAL MAE = 0.18150000000000066


48 FOLD Start!
VAL MAE = 0.049000000000001265


49 FOLD Start!
VAL MAE = 0.006499999999999506


50 FOLD Start!
VAL MAE = 0.07800000000000029


51 FOLD Start!
VAL MAE = 0.2855000000000012


52 FOLD Start!
VAL MAE = 0.0649999999999995


53 FOLD Start!
VAL MAE = 0.3550000000000022


54 FOLD Start!
VAL MAE = 0.6350000000000016


55 FOLD Start!
VAL MAE = 0.17900000000000071


56 FOLD Start!
VAL MAE = 0.3839999999999981


57 FOLD Start!
VAL MAE = 0.3135000000000008


58 FOLD Start!
VAL MAE = 0.3244999999999987


59 FOLD Start!
VAL MAE = 0.0114999999999994


60 FOLD Start!
VAL MAE = 0.3119999999999994


61 FOLD Start!
VAL MAE = 0.022999999999999687


62 FOLD Start!
VAL MAE = 0.01750000000000007


63 FOLD Start!
VAL MAE = 0.06049999999999889


64 FOLD Start!
VAL MAE = 0.13500000000000156


65 FOLD Start!
VAL MAE = 0.27999999999999936


66 FOLD Start!
VAL MAE = 0.192499999999999


67 FOLD Start!
VAL MAE = 0.22050000000000036


68 FOLD Start!
VAL MAE = 0.26149999999999984


69 FOLD Start!
VAL MAE = 0.011500000000000732


70 FOLD Start!
VAL MAE = 0.3524999999999996


71 FOLD Start!
VAL MAE = 0.11499999999999844


72 FOLD Start!
VAL MAE = 0.4005000000000005


73 FOLD Start!
VAL MAE = 0.661500000000002


74 FOLD Start!
VAL MAE = 0.02949999999999875


75 FOLD Start!
VAL MAE = 0.2935000000000021

In [18]:
rf_pred2 = np.zeros((target.shape[0]))
for i, idx in enumerate(zip(lo.split(X, y2))) :
    print(f'{i + 1} FOLD Start!')
    tr_x, tr_y = X.iloc[idx[0][0]], y2.iloc[idx[0][0]]
    val_x, val_y = X.iloc[idx[0][1]], y2.iloc[idx[0][1]]
    
    rf = RandomForestRegressor(random_state = 42, n_estimators = 100, criterion = 'mae', max_depth = 4)
    
    rf.fit(tr_x, tr_y)
    val_pred = rf.predict(val_x)
    val_mae = mean_absolute_error(val_y, val_pred)
    print(f'VAL MAE = {val_mae}')
    fold_pred = rf.predict(target) / 75
    
    rf_pred2 += fold_pred
    
    print('\n')

1 FOLD Start!
VAL MAE = 0.005500000000000116


2 FOLD Start!
VAL MAE = 0.03199999999999914


3 FOLD Start!
VAL MAE = 0.13400000000000034


4 FOLD Start!
VAL MAE = 0.4295000000000013


5 FOLD Start!
VAL MAE = 0.014000000000000346


6 FOLD Start!
VAL MAE = 0.11149999999999949


7 FOLD Start!
VAL MAE = 0.1124999999999998


8 FOLD Start!
VAL MAE = 0.23149999999999848


9 FOLD Start!
VAL MAE = 0.15600000000000058


10 FOLD Start!
VAL MAE = 0.031500000000001194


11 FOLD Start!
VAL MAE = 0.1904999999999999


12 FOLD Start!
VAL MAE = 0.05450000000000066


13 FOLD Start!
VAL MAE = 0.15299999999999936


14 FOLD Start!
VAL MAE = 0.012999999999999928


15 FOLD Start!
VAL MAE = 0.02199999999999966


16 FOLD Start!
VAL MAE = 0.06199999999999983


17 FOLD Start!
VAL MAE = 0.1885000000000021


18 FOLD Start!
VAL MAE = 0.03350000000000097


19 FOLD Start!
VAL MAE = 0.004000000000000364


20 FOLD Start!
VAL MAE = 0.021000000000000574


21 FOLD Start!
VAL MAE = 0.11900000000000022


22 FOLD Start!
VAL MAE = 0.20350000000000035


23 FOLD Start!
VAL MAE = 0.28150000000000075


24 FOLD Start!
VAL MAE = 0.44250000000000034


25 FOLD Start!
VAL MAE = 0.07600000000000096


26 FOLD Start!
VAL MAE = 0.3714999999999973


27 FOLD Start!
VAL MAE = 0.2705000000000011


28 FOLD Start!
VAL MAE = 0.05950000000000011


29 FOLD Start!
VAL MAE = 0.04599999999999982


30 FOLD Start!
VAL MAE = 0.10200000000000076


31 FOLD Start!
VAL MAE = 0.14750000000000174


32 FOLD Start!
VAL MAE = 0.016000000000000264


33 FOLD Start!
VAL MAE = 0.5594999999999997


34 FOLD Start!
VAL MAE = 0.28699999999999837


35 FOLD Start!
VAL MAE = 0.06399999999999872


36 FOLD Start!
VAL MAE = 0.009000000000000119


37 FOLD Start!
VAL MAE = 0.21649999999999925


38 FOLD Start!
VAL MAE = 0.09999999999999962


39 FOLD Start!
VAL MAE = 0.1414999999999993


40 FOLD Start!
VAL MAE = 0.27899999999999947


41 FOLD Start!
VAL MAE = 0.29450000000000043


42 FOLD Start!
VAL MAE = 0.10300000000000065


43 FOLD Start!
VAL MAE = 0.06449999999999934


44 FOLD Start!
VAL MAE = 0.014999999999999819


45 FOLD Start!
VAL MAE = 0.2154999999999998


46 FOLD Start!
VAL MAE = 0.05650000000000044


47 FOLD Start!
VAL MAE = 0.17950000000000044


48 FOLD Start!
VAL MAE = 0.27850000000000064


49 FOLD Start!
VAL MAE = 0.1850000000000005


50 FOLD Start!
VAL MAE = 0.16300000000000092


51 FOLD Start!
VAL MAE = 0.12100000000000027


52 FOLD Start!
VAL MAE = 0.05150000000000032


53 FOLD Start!
VAL MAE = 0.01450000000000018


54 FOLD Start!
VAL MAE = 0.28599999999999914


55 FOLD Start!
VAL MAE = 0.0010000000000000842


56 FOLD Start!
VAL MAE = 0.34549999999999925


57 FOLD Start!
VAL MAE = 0.18849999999999945


58 FOLD Start!
VAL MAE = 0.10299999999999968


59 FOLD Start!
VAL MAE = 0.22599999999999976


60 FOLD Start!
VAL MAE = 0.41449999999999854


61 FOLD Start!
VAL MAE = 0.1504999999999992


62 FOLD Start!
VAL MAE = 0.4919999999999993


63 FOLD Start!
VAL MAE = 0.40549999999999997


64 FOLD Start!
VAL MAE = 0.09800000000000075


65 FOLD Start!
VAL MAE = 0.0660000000000002


66 FOLD Start!
VAL MAE = 0.05250000000000021


67 FOLD Start!
VAL MAE = 0.06150000000000033


68 FOLD Start!
VAL MAE = 0.09650000000000003


69 FOLD Start!
VAL MAE = 0.14749999999999908


70 FOLD Start!
VAL MAE = 0.1839999999999984


71 FOLD Start!
VAL MAE = 0.0589999999999995


72 FOLD Start!
VAL MAE = 0.25600000000000045


73 FOLD Start!
VAL MAE = 0.0649999999999995


74 FOLD Start!
VAL MAE = 0.13799999999999923


75 FOLD Start!
VAL MAE = 0.05000000000000093

In [21]:
submission = pd.read_csv("sample_submission.csv")

In [22]:
submission.iloc[:, 1] = rf_pred1
submission.iloc[:, 2] = rf_pred2

In [23]:
submission.to_csv('1020_rf_1st.csv', index = False)