In [1]:
import pandas as pd
import numpy as np

In [2]:
train = pd.read_csv('train.csv')
test = pd.read_csv('test.csv')

In [6]:
meta_x = pd.read_csv('./meta/x_feature_info.csv')
meta_y = pd.read_csv('./meta/y_feature_info.csv')
meta = pd.read_csv('./meta/y_feature_spec_info.csv')

In [7]:
meta

   Feature    최소    최대
0     Y_01   0.2   2.0
1     Y_02   0.2   2.1
2     Y_03   0.2   2.1
3     Y_04   7.0  19.0
4     Y_05  22.0  36.5
5     Y_06 -19.2  19.0
6     Y_07   2.4   4.0
7     Y_08 -29.2 -24.0
8     Y_09 -29.2 -24.0
9     Y_10 -30.6 -20.0
10    Y_11  19.6  26.6
11    Y_12 -29.2 -24.0
12    Y_13 -29.2 -24.0
13    Y_14 -29.2 -24.0

In [5]:
meta_x

   Feature                        설명
0     X_01  PCB 체결 시 단계별 누름량(Step 1)
1     X_02  PCB 체결 시 단계별 누름량(Step 2)
2     X_03                방열 재료 1 무게
3     X_04               1차 검사 통과 여부
4     X_05  PCB 체결 시 단계별 누름량(Step 3)
5     X_06  PCB 체결 시 단계별 누름량(Step 4)
6     X_07                방열 재료 1 면적
7     X_08                방열 재료 2 면적
8     X_09                방열 재료 3 면적
9     X_10                방열 재료 2 무게
10    X_11                방열 재료 3 무게
11    X_12              커넥터 위치 기준 좌표
12    X_13        각 안테나 패드 위치(높이) 차이
13    X_14              1번 안테나 패드 위치
14    X_15              2번 안테나 패드 위치
15    X_16              3번 안테나 패드 위치
16    X_17              4번 안테나 패드 위치
17    X_18              5번 안테나 패드 위치
18    X_19              1번 스크류 삽입 깊이
19    X_20              2번 스크류 삽입 깊이
20    X_21              3번 스크류 삽입 깊이
21    X_22              4번 스크류 삽입 깊이
22    X_23               2차 검사 통과 여부
23    X_24               커넥터 1번 핀 치수
24    X_25               커넥터 2번 핀 치수
25    X_26               커넥터 3번 핀 치수
26    X_27               커넥터 4번 핀 치수
27    X_28               커넥터 5번 핀 치수
28    X_29               커넥터 6번 핀 치수
29    X_30                스크류 삽입 깊이1
30    X_31                스크류 삽입 깊이2
31    X_32                스크류 삽입 깊이3
32    X_33                스크류 삽입 깊이4
33    X_34         스크류 체결 시 분당 회전수 1
34    X_35         스크류 체결 시 분당 회전수 2
35    X_36         스크류 체결 시 분당 회전수 3
36    X_37         스크류 체결 시 분당 회전수 4
37    X_38          하우징 PCB 안착부 1 치수
38    X_39          하우징 PCB 안착부 2 치수
39    X_40          하우징 PCB 안착부 3 치수
40    X_41        레이돔 치수 (안테나 1번 부위)
41    X_42        레이돔 치수 (안테나 2번 부위)
42    X_43        레이돔 치수 (안테나 3번 부위)
43    X_44        레이돔 치수 (안테나 4번 부위)
44    X_45            안테나 부분 레이돔 기울기
45    X_46                실란트 본드 소요량
46    X_47               3차 검사 통과 여부
47    X_48               4차 검사 통과 여부
48    X_49            Cal 투입 전 대기 시간
49    X_50            RF1 부분 SMT 납 량
50    X_51            RF2 부분 SMT 납 량
51    X_52            RF3 부분 SMT 납 량
52    X_53            RF4 부분 SMT 납 량
53    X_54            RF5 부분 SMT 납 량
54    X_55            RF6 부분 SMT 납 량
55    X_56            RF7 부분 SMT 납 량

In [4]:
meta_y

   Feature                   설명
0     Y_01  안테나 Gain 평균 (각도1)
1     Y_02        안테나 1 Gain 편차
2     Y_03        안테나 2 Gain 편차
3     Y_04          평균 신호대 잡음비
4     Y_05    안테나 Gain 평균 (각도2)
5     Y_06     신호대 잡음비  (각도1)
6     Y_07  안테나 Gain 평균 (각도3)
7     Y_08     신호대 잡음비  (각도2)
8     Y_09     신호대 잡음비  (각도3)
9     Y_10     신호대 잡음비  (각도4)
10    Y_11    안테나 Gain 평균 (각도4)
11    Y_12     신호대 잡음비  (각도5)
12    Y_13     신호대 잡음비  (각도6)
13    Y_14     신호대 잡음비  (각도7)

In [8]:
train.head()

,ID,X_01,X_02,X_03,X_04,X_05,X_06,X_07,X_08,X_09,...,Y_05,Y_06,Y_07,Y_08,Y_09,Y_10,Y_11,Y_12,Y_13,Y_14
0,TRAIN_00001,70.544,103.320,67.47,1,101.892,74.983,29.45,62.38,245.71,...,29.632,16.083,4.276,-25.381,-25.529,-22.769,23.792,-25.470,-25.409,-25.304
1,TRAIN_00002,69.524,103.321,65.17,1,101.944,72.943,28.73,61.23,233.61,...,33.179,16.736,3.229,-26.619,-26.523,-22.574,24.691,-26.253,-26.497,-26.438
2,TRAIN_00003,72.583,103.320,64.07,1,103.153,72.943,28.81,105.77,272.20,...,31.801,17.080,2.839,-26.238,-26.216,-22.169,24.649,-26.285,-26.215,-26.370
3,TRAIN_00004,71.563,103.320,67.57,1,101.971,77.022,28.92,115.21,255.36,...,34.503,17.143,3.144,-25.426,-25.079,-21.765,24.913,-25.254,-25.021,-25.345
4,TRAIN_00005,69.524,103.320,63.57,1,101.981,70.904,29.68,103.38,241.46,...,32.602,17.569,3.138,-25.376,-25.242,-21.072,25.299,-25.072,-25.195,-24.974

In [9]:
test.head()

,ID,X_01,X_02,X_03,X_04,X_05,X_06,X_07,X_08,X_09,...,X_47,X_48,X_49,X_50,X_51,X_52,X_53,X_54,X_55,X_56
0,TEST_00001,68.504,103.321,76.67,1,101.867,73.963,30.51,63.57,239.80,...,1,1,17227.63,138.130429,129.460682,141.506570,133.427229,129.711498,133.138096,121.859684
1,TEST_00002,67.485,103.320,69.37,1,101.992,67.845,28.03,116.99,189.23,...,1,1,17134.53,136.148839,128.266277,145.911745,131.196417,132.411480,133.629025,124.178623
2,TEST_00003,69.524,103.320,68.97,1,101.884,77.022,29.65,205.68,214.93,...,1,1,14860.83,120.447446,119.988804,132.099908,120.450155,130.051708,128.252972,114.475628
3,TEST_00004,69.524,103.320,65.87,1,101.866,73.963,28.15,103.38,180.80,...,1,1,15252.53,133.994695,125.069180,147.507669,123.142653,125.963665,139.666592,126.589253
4,TEST_00005,73.603,103.321,66.67,1,101.891,74.983,29.92,71.20,231.93,...,1,1,10752.23,137.918202,135.116192,138.600473,127.173033,137.252712,134.411335,124.020016

In [8]:
X = train.loc[:, 'X_01':'X_56']
y = train.loc[:, 'Y_01':]

In [18]:
target = test[X.columns]

In [21]:
from catboost import CatBoostRegressor
from sklearn.model_selection import KFold
from sklearn.metrics import make_scorer, mean_squared_error

In [29]:
def lg_nrmse(gt, preds):
    # 각 Y Feature별 NRMSE 총합
    # Y_01 ~ Y_08 까지 20% 가중치 부여
    all_nrmse = []
    for idx in range(14): # ignore 'ID'
        rmse = mean_squared_error(gt.iloc[:,idx], preds[:,idx], squared = False)
        nrmse = rmse / np.mean(np.abs(gt.iloc[:,idx]))
        all_nrmse.append(nrmse)
    score = 1.2 * np.sum(all_nrmse[:8]) + 1.0 * np.sum(all_nrmse[8:15])
    return score

In [23]:
kf = KFold(n_splits = 10, random_state = 42, shuffle = True)

In [34]:
NRMSES = []
cb_pred = np.zeros((target.shape[0], 14))
for i, idx in enumerate(kf.split(X, y)) :
    tr_x, tr_y = X.loc[idx[0]], y.loc[idx[0]]
    val_x, val_y = X.loc[idx[1]], y.loc[idx[1]]
    
    cb = CatBoostRegressor(random_state = 42, max_depth = 5, n_estimators = 10000, learning_rate = 0.03, objective = 'MultiRMSE')
    cb.fit(tr_x, tr_y, eval_set = [(tr_x, tr_y), (val_x, val_y)], early_stopping_rounds = 500, verbose = 2000)
    
    val_pred = cb.predict(val_x)
    NRMSE = lg_nrmse(val_y, val_pred)
    print(f"{i + 1} Fold NRMSE = {NRMSE}")
    NRMSES.append(NRMSE)
    
    fold_pred = cb.predict(target) / kf.n_splits
    cb_pred += fold_pred

0:	learn: 4.6536800	test: 4.6536800	test1: 4.5019109	best: 4.5019109 (0)	total: 29.7ms	remaining: 4m 56s
2000:	learn: 4.1762268	test: 4.1762268	test1: 4.3413832	best: 4.3413830 (1999)	total: 51.3s	remaining: 3m 24s
4000:	learn: 3.9459986	test: 3.9459986	test1: 4.3226382	best: 4.3217270 (3502)	total: 1m 42s	remaining: 2m 33s
Stopped by overfitting detector  (500 iterations wait)

bestTest = 4.321726975
bestIteration = 3502

Shrink model to first 3503 iterations.
1 Fold NRMSE = 1.923625870778375
0:	learn: 4.6402459	test: 4.6402459	test1: 4.6190011	best: 4.6190011 (0)	total: 32ms	remaining: 5m 20s
2000:	learn: 4.1733371	test: 4.1733371	test1: 4.4463806	best: 4.4463806 (2000)	total: 49.5s	remaining: 3m 17s
4000:	learn: 3.9474830	test: 3.9474830	test1: 4.4303482	best: 4.4301575 (3958)	total: 1m 39s	remaining: 2m 29s
6000:	learn: 3.7533240	test: 3.7533240	test1: 4.4241050	best: 4.4236951 (5656)	total: 2m 29s	remaining: 1m 39s
Stopped by overfitting detector  (500 iterations wait)

bestTest = 4.423695087
bestIteration = 5656

Shrink model to first 5657 iterations.
2 Fold NRMSE = 1.9445557555825561
0:	learn: 4.6012787	test: 4.6012787	test1: 4.9603414	best: 4.9603414 (0)	total: 29.1ms	remaining: 4m 51s
2000:	learn: 4.1503488	test: 4.1503488	test1: 4.7767718	best: 4.7766441 (1998)	total: 48.7s	remaining: 3m 14s
4000:	learn: 3.9280526	test: 3.9280526	test1: 4.7590841	best: 4.7589387 (3851)	total: 1m 36s	remaining: 2m 24s
6000:	learn: 3.7369741	test: 3.7369741	test1: 4.7499764	best: 4.7499433 (5998)	total: 2m 24s	remaining: 1m 36s
8000:	learn: 3.5635942	test: 3.5635942	test1: 4.7437996	best: 4.7434691 (7878)	total: 3m 13s	remaining: 48.3s
Stopped by overfitting detector  (500 iterations wait)

bestTest = 4.742810058
bestIteration = 8199

Shrink model to first 8200 iterations.
3 Fold NRMSE = 1.990752823695778
0:	learn: 4.6386024	test: 4.6386024	test1: 4.6402587	best: 4.6402587 (0)	total: 32ms	remaining: 5m 20s
2000:	learn: 4.1697563	test: 4.1697563	test1: 4.4594359	best: 4.4594359 (2000)	total: 47.5s	remaining: 3m 9s
4000:	learn: 3.9444959	test: 3.9444959	test1: 4.4420398	best: 4.4417457 (3917)	total: 1m 34s	remaining: 2m 22s
6000:	learn: 3.7527888	test: 3.7527888	test1: 4.4351716	best: 4.4347566 (5963)	total: 2m 23s	remaining: 1m 35s
Stopped by overfitting detector  (500 iterations wait)

bestTest = 4.431926546
bestIteration = 6874

Shrink model to first 6875 iterations.
4 Fold NRMSE = 1.949279509629425
0:	learn: 4.6491504	test: 4.6491504	test1: 4.5400127	best: 4.5400127 (0)	total: 29.6ms	remaining: 4m 56s
2000:	learn: 4.1652843	test: 4.1652843	test1: 4.4511189	best: 4.4500241 (1519)	total: 47.5s	remaining: 3m 9s
Stopped by overfitting detector  (500 iterations wait)

bestTest = 4.450024077
bestIteration = 1519

Shrink model to first 1520 iterations.
5 Fold NRMSE = 1.950597820371477
0:	learn: 4.6372055	test: 4.6372055	test1: 4.6522262	best: 4.6522262 (0)	total: 32.2ms	remaining: 5m 21s
2000:	learn: 4.1757160	test: 4.1757160	test1: 4.4429300	best: 4.4428930 (1998)	total: 46.9s	remaining: 3m 7s
4000:	learn: 3.9484482	test: 3.9484482	test1: 4.4227530	best: 4.4227473 (3996)	total: 1m 34s	remaining: 2m 21s
6000:	learn: 3.7545203	test: 3.7545203	test1: 4.4159272	best: 4.4158314 (5988)	total: 2m 22s	remaining: 1m 35s
Stopped by overfitting detector  (500 iterations wait)

bestTest = 4.414617167
bestIteration = 6527

Shrink model to first 6528 iterations.
6 Fold NRMSE = 1.9416298712514704
0:	learn: 4.6358102	test: 4.6358102	test1: 4.6589169	best: 4.6589169 (0)	total: 30.3ms	remaining: 5m 2s
2000:	learn: 4.1671074	test: 4.1671074	test1: 4.4917634	best: 4.4917634 (2000)	total: 48.4s	remaining: 3m 13s
4000:	learn: 3.9378128	test: 3.9378128	test1: 4.4814870	best: 4.4812541 (3828)	total: 1m 39s	remaining: 2m 29s
Stopped by overfitting detector  (500 iterations wait)

bestTest = 4.479912306
bestIteration = 4724

Shrink model to first 4725 iterations.
7 Fold NRMSE = 1.979584057269958
0:	learn: 4.6592277	test: 4.6592277	test1: 4.4527963	best: 4.4527963 (0)	total: 28.8ms	remaining: 4m 48s
2000:	learn: 4.1832512	test: 4.1832512	test1: 4.2806000	best: 4.2803706 (1988)	total: 48.5s	remaining: 3m 13s
4000:	learn: 3.9533191	test: 3.9533191	test1: 4.2651647	best: 4.2642908 (3864)	total: 1m 36s	remaining: 2m 24s
Stopped by overfitting detector  (500 iterations wait)

bestTest = 4.262923647
bestIteration = 4436

Shrink model to first 4437 iterations.
8 Fold NRMSE = 1.9114307888801956
0:	learn: 4.6256763	test: 4.6256763	test1: 4.7570127	best: 4.7570127 (0)	total: 29.4ms	remaining: 4m 54s
2000:	learn: 4.1613904	test: 4.1613904	test1: 4.5337708	best: 4.5337205 (1955)	total: 46.8s	remaining: 3m 7s
4000:	learn: 3.9355955	test: 3.9355955	test1: 4.5099759	best: 4.5093795 (3791)	total: 1m 34s	remaining: 2m 21s
Stopped by overfitting detector  (500 iterations wait)

bestTest = 4.501767593
bestIteration = 5225

Shrink model to first 5226 iterations.
9 Fold NRMSE = 1.9750193614691254
0:	learn: 4.6436018	test: 4.6436018	test1: 4.5855912	best: 4.5855912 (0)	total: 31.1ms	remaining: 5m 11s
2000:	learn: 4.1735831	test: 4.1735831	test1: 4.4120351	best: 4.4119373 (1983)	total: 46.8s	remaining: 3m 7s
4000:	learn: 3.9413041	test: 3.9413041	test1: 4.3986126	best: 4.3983638 (3853)	total: 1m 34s	remaining: 2m 22s
6000:	learn: 3.7463635	test: 3.7463635	test1: 4.3938706	best: 4.3926279 (5503)	total: 2m 25s	remaining: 1m 37s
Stopped by overfitting detector  (500 iterations wait)

bestTest = 4.392627925
bestIteration = 5503

Shrink model to first 5504 iterations.
10 Fold NRMSE = 1.9277032516789956

In [35]:
np.mean(NRMSES)

1.9494179110607355

In [38]:
submission = pd.read_csv('sample_submission.csv')

In [40]:
submission.iloc[:, 1:] = cb_pred

In [41]:
submission.to_csv('1st.csv', index = False)